"""empty message

Revision ID: aa5acdaded5f
Revises: 0cd416f5a7d2
Create Date: 2020-09-28 21:19:27.968305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa5acdaded5f'
down_revision = '0cd416f5a7d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_time_top_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_all_time_top_results_timestamp'), 'all_time_top_results', ['timestamp'], unique=False)
    op.create_table('all_time_top_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('term', sa.String(), nullable=True),
    sa.Column('hits', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_all_time_top_searches_timestamp'), 'all_time_top_searches', ['timestamp'], unique=False)
    op.create_table('all_time_usage_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('results_clicked', sa.Integer(), nullable=True),
    sa.Column('attribution_buttonclicks', sa.Integer(), nullable=True),
    sa.Column('survey_responses', sa.Integer(), nullable=True),
    sa.Column('source_clicked', sa.Integer(), nullable=True),
    sa.Column('creator_clicked', sa.Integer(), nullable=True),
    sa.Column('shared_social', sa.Integer(), nullable=True),
    sa.Column('sessions', sa.Integer(), nullable=True),
    sa.Column('searches', sa.Integer(), nullable=True),
    sa.Column('attribution_referer_hits', sa.Integer(), nullable=True),
    sa.Column('images', sa.Integer(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('avg_searches_per_session', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_all_time_usage_reports_timestamp'), 'all_time_usage_reports', ['timestamp'], unique=False)
    op.create_table('daily_attribution_referer_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_attribution_referer_report_domain'), 'daily_attribution_referer_report', ['domain'], unique=False)
    op.create_index(op.f('ix_daily_attribution_referer_report_timestamp'), 'daily_attribution_referer_report', ['timestamp'], unique=False)
    op.create_table('daily_source_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('result_clicks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_source_report_source_id'), 'daily_source_report', ['source_id'], unique=False)
    op.create_index(op.f('ix_daily_source_report_timestamp'), 'daily_source_report', ['timestamp'], unique=False)
    op.create_table('daily_top_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_top_results_timestamp'), 'daily_top_results', ['timestamp'], unique=False)
    op.create_table('daily_top_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('term', sa.String(), nullable=True),
    sa.Column('hits', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_top_searches_timestamp'), 'daily_top_searches', ['timestamp'], unique=False)
    op.create_table('daily_usage_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('results_clicked', sa.Integer(), nullable=True),
    sa.Column('attribution_buttonclicks', sa.Integer(), nullable=True),
    sa.Column('survey_responses', sa.Integer(), nullable=True),
    sa.Column('source_clicked', sa.Integer(), nullable=True),
    sa.Column('creator_clicked', sa.Integer(), nullable=True),
    sa.Column('shared_social', sa.Integer(), nullable=True),
    sa.Column('sessions', sa.Integer(), nullable=True),
    sa.Column('searches', sa.Integer(), nullable=True),
    sa.Column('attribution_referer_hits', sa.Integer(), nullable=True),
    sa.Column('images', sa.Integer(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('avg_searches_per_session', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_usage_reports_timestamp'), 'daily_usage_reports', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_usage_reports_timestamp'), table_name='daily_usage_reports')
    op.drop_table('daily_usage_reports')
    op.drop_index(op.f('ix_daily_top_searches_timestamp'), table_name='daily_top_searches')
    op.drop_table('daily_top_searches')
    op.drop_index(op.f('ix_daily_top_results_timestamp'), table_name='daily_top_results')
    op.drop_table('daily_top_results')
    op.drop_index(op.f('ix_daily_source_report_timestamp'), table_name='daily_source_report')
    op.drop_index(op.f('ix_daily_source_report_source_id'), table_name='daily_source_report')
    op.drop_table('daily_source_report')
    op.drop_index(op.f('ix_daily_attribution_referer_report_timestamp'), table_name='daily_attribution_referer_report')
    op.drop_index(op.f('ix_daily_attribution_referer_report_domain'), table_name='daily_attribution_referer_report')
    op.drop_table('daily_attribution_referer_report')
    op.drop_index(op.f('ix_all_time_usage_reports_timestamp'), table_name='all_time_usage_reports')
    op.drop_table('all_time_usage_reports')
    op.drop_index(op.f('ix_all_time_top_searches_timestamp'), table_name='all_time_top_searches')
    op.drop_table('all_time_top_searches')
    op.drop_index(op.f('ix_all_time_top_results_timestamp'), table_name='all_time_top_results')
    op.drop_table('all_time_top_results')
    # ### end Alembic commands ###
