"""empty message

Revision ID: ccf6704158e5
Revises: 
Create Date: 2019-07-25 22:08:54.195070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ccf6704158e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detail_page_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('result_uuid', postgresql.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('ATTRIBUTION_CLICKED', 'REUSE_SURVEY', 'SOURCE_CLICKED', 'CREATOR_CLICKED', 'SHARED_SOCIAL', name='detailpageevents'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detail_page_event_date'), 'detail_page_event', ['date'], unique=False)
    op.create_index(op.f('ix_detail_page_event_event_type'), 'detail_page_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_detail_page_event_result_uuid'), 'detail_page_event', ['result_uuid'], unique=False)
    op.create_table('result_clicked_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('session_uuid', postgresql.UUID(), nullable=True),
    sa.Column('result_uuid', postgresql.UUID(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('result_rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_clicked_event_date'), 'result_clicked_event', ['date'], unique=False)
    op.create_index(op.f('ix_result_clicked_event_query'), 'result_clicked_event', ['query'], unique=False)
    op.create_index(op.f('ix_result_clicked_event_result_uuid'), 'result_clicked_event', ['result_uuid'], unique=False)
    op.create_index(op.f('ix_result_clicked_event_session_uuid'), 'result_clicked_event', ['session_uuid'], unique=False)
    op.create_table('search_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('session_uuid', postgresql.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_event_date'), 'search_event', ['date'], unique=False)
    op.create_index(op.f('ix_search_event_query'), 'search_event', ['query'], unique=False)
    op.create_index(op.f('ix_search_event_session_uuid'), 'search_event', ['session_uuid'], unique=False)
    op.create_table('search_rating_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_rating_event_date'), 'search_rating_event', ['date'], unique=False)
    op.create_index(op.f('ix_search_rating_event_query'), 'search_rating_event', ['query'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_rating_event_query'), table_name='search_rating_event')
    op.drop_index(op.f('ix_search_rating_event_date'), table_name='search_rating_event')
    op.drop_table('search_rating_event')
    op.drop_index(op.f('ix_search_event_session_uuid'), table_name='search_event')
    op.drop_index(op.f('ix_search_event_query'), table_name='search_event')
    op.drop_index(op.f('ix_search_event_date'), table_name='search_event')
    op.drop_table('search_event')
    op.drop_index(op.f('ix_result_clicked_event_session_uuid'), table_name='result_clicked_event')
    op.drop_index(op.f('ix_result_clicked_event_result_uuid'), table_name='result_clicked_event')
    op.drop_index(op.f('ix_result_clicked_event_query'), table_name='result_clicked_event')
    op.drop_index(op.f('ix_result_clicked_event_date'), table_name='result_clicked_event')
    op.drop_table('result_clicked_event')
    op.drop_index(op.f('ix_detail_page_event_result_uuid'), table_name='detail_page_event')
    op.drop_index(op.f('ix_detail_page_event_event_type'), table_name='detail_page_event')
    op.drop_index(op.f('ix_detail_page_event_date'), table_name='detail_page_event')
    op.drop_table('detail_page_event')
    # ### end Alembic commands ###
