from rest_framework import serializers
from rest_framework.serializers import ModelSerializer
from cccatalog.api.models import Image
from cccatalog.api.serializers.search_serializers import ImageSerializer


class ImageDetailTagSerializer(serializers.Serializer):
    name = serializers.CharField(
        required=False,
        help_text="The name of a detailed tag."
    )
    accuracy = serializers.FloatField(
        required=False,
        help_text="The accuracy of a machine-generated tag. Human-generated "
                  "tags do not have an accuracy field."
    )
    provider = serializers.CharField(
        required=False,
        help_text="The source of a tag. Usually, it matches the provider of "
                  "the image, but it can also be generated by a third party."
    )


class ImageDetailSerializer(ModelSerializer, ImageSerializer):
    """
    A single image with some additional fields, such as view count. Unlike
    ImageSerializer, the detail view comes from the database rather than
    Elasticsearch.
    """
    view_count = serializers.IntegerField(
        required=False,
        help_text="The number of times that an image has been viewed. "
    )
    tags = ImageDetailTagSerializer(
        many=True,
        help_text="Tags with detailed metadata, such as accuracy and provider."
    )
    id = serializers.CharField(
        help_text='The unique ID of an image.',
        source='identifier'
    )

    class Meta:
        model = Image
        fields = ('title', 'id', 'creator', 'creator_url', 'tags',
                  'url', 'thumbnail', 'provider', 'source', 'license',
                  'license_version', 'foreign_landing_url', 'meta_data',
                  'view_count')
