COLOR := "\\033[0;34m"
NO_COLOR := "\\033[0m"


# Show all available recipes
@_default:
    printf "\n{{ COLOR }}# Vale (path: \`.vale/\`)\n"
    printf "===================={{ NO_COLOR }}\n"
    just --list --unsorted


# Build a local version of `openverse-vale:local` for testing
build:
    docker build . -t openverse-vale:local


# Run `openverse-vale:local` image using a configuration that matches pre-commit's. Pass files relative to repository root.
run +files: build
    docker run --rm -it -v $PWD/..:/src:rw,Z --workdir=/src openverse-vale:local {{ files }}
