set dotenv-load := false

# Show all available recipes
@_default:
    echo "############"
    echo "# Frontend #"
    echo "############"
    just --list --unsorted


# Run a package.json script via pnpm
run *args:
    pnpm run {{ args }}
