name: openverse/build-docs
description: Build Openverse full-stack docs

inputs:
  github_token:
    required: true
    description: GitHub token to use for issue link resolution in documentation

runs:
  using: "composite"
  steps:
    - name: Build Sphinx
      shell: bash
      env:
        LINK_ISSUES_GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        # Pass -W to fail CI if warnings exist
        just documentation/build -W

    - name: Install translations
      shell: bash
      run: |
        just frontend/run i18n

    # Storybook will be available at `/storybook`
    - name: Merge all docs
      shell: bash
      run: |
        mv documentation/_build /tmp/docs
