# Whether this GitHub repo is engineering related
engineering_project: true
# Name of the repository/project in English
english_name: CC Search
# All technologies used
technologies: JavaScript, Vue.js
# Whether this repository should be featured on the CC Open Source site
featured: false
# Slack channel name
slack: 'cc-search'
