
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const ADD_IMAGE_TO_LIST = 'ADD_IMAGE_TO_LIST';
export const FETCH_IMAGE = 'FETCH_IMAGE';
export const FETCH_IMAGES = 'FETCH_IMAGES';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
