export const FETCH_IMAGE_STATS = 'FETCH_IMAGE_STATS';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const FETCH_IMAGE = 'FETCH_IMAGE';
export const FETCH_IMAGES = 'FETCH_IMAGES';
export const FETCH_RELATED_IMAGES = 'FETCH_RELATED_IMAGES';
export const COPY_ATTRIBUTION = 'COPY_ATTRIBUTION';
