# Generated by Django 2.0.5 on 2018-07-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),  # 0002 was merged into 0001 to protect FK constraint
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.RunSQL('ALTER TABLE image ALTER view_count SET DEFAULT 0')
    ]
