# Generated by Django 2.0.5 on 2018-08-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180803_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='watermarked',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
