# Generated by Django 2.2.10 on 2020-04-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200423_1526'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeletedImages',
            new_name='DeletedImage',
        ),
        migrations.RenameModel(
            old_name='MatureImages',
            new_name='MatureImage',
        ),
        migrations.AlterField(
            model_name='imagereport',
            name='status',
            field=models.CharField(choices=[('pending_review', 'pending_review'), ('mature_filter', 'mature_filter'), ('deindex', 'deindex'), ('do_nothing', 'do_nothing')], default='pending', max_length=20),
        ),
    ]
