# Generated by Django 2.2.10 on 2020-04-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200423_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagereport',
            name='status',
            field=models.CharField(choices=[('pending_review', 'pending_review'), ('mature_filtered', 'mature_filtered'), ('deindexed', 'deindexed'), ('no_action', 'no_action')], default='pending_review', max_length=20),
        ),
        migrations.DeleteModel(
            name='ImageTags',
        ),
    ]
