# Generated by Django 2.2.10 on 2020-05-15 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_imagereport_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagereport',
            old_name='date',
            new_name='created_at',
        ),
    ]
