# Generated by Django 3.2.7 on 2021-10-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_audio_set_thumbs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='url',
            field=models.URLField(blank=True, help_text='The actual URL to the media file.', max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='audioset',
            name='url',
            field=models.URLField(blank=True, help_text='The actual URL to the media file.', max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(blank=True, help_text='The actual URL to the media file.', max_length=1000, null=True, unique=True),
        ),
    ]
