# Generated by Django 3.2.7 on 2021-10-13 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_nullable_urls'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='audioset',
            table='audioset',
        ),
    ]
