# Generated by Django 4.0.6 on 2022-07-21 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_throttledapplication_client_secret'),
        ('api', '0048_alter_throttledapplication_rate_limit_model'),
    ]

    operations = [
    ]
