# Generated by Django 4.0.6 on 2022-09-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_merge_migrations_number_48'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deletedaudio',
            options={'verbose_name_plural': 'Deleted audio'},
        ),
        migrations.AlterModelOptions(
            name='matureaudio',
            options={'verbose_name_plural': 'Mature audio'},
        ),
    ]
