import { randomItem } from "./jslib-shim"

export const SAMPLE_QUERY_TERMS = [
  "cat",
  "outsourced accountant",
  "plane",
  "tree leaf nutrition",
  "games",
  "French president",
  "Morpho menelaus",
  "French government",
  "Dom Quixote de la Mancha",
  "graphs",
  "javier milei",
  "art",
  "intergeneration",
  "channel",
  "hampton court palace",
  "james earl jones",
  "Juan López",
  "liverpool fc",
  "poster",
  "school clip art",
  "castle",
  "people",
  "colon cancer",
  "broken water dam",
  "jillian michaels",
  "Spilanthes acmella",
  "dolphins football helmet",
  "new york",
  "starbucks pumpkin chai",
  "car wheel",
  "Justin Tranter",
  "impregnating water with fixed air",
  "Cartoon boy and girl close relationship",
  "nebula",
  "Puffin tufted",
  "a guy",
  "men faces",
  "men",
  "Finger of death Antarctica",
  "faces",
  "harry styles",
  "chris pratt",
  "dwayne johnson",
  "Johnny deep",
  "Ryan gosling",
  "Ryan gossling",
  "zac efron",
  "zac efrn",
  "Justin bieber",
  "Ariana grande",
  "Betty white",
  "obama",
  "Michael jackson",
  "wine glasses",
  "flag clip art",
  "heat pump",
  "herbes folles",
  "mechanic shop",
  "backing track",
  "Thomas Cromwell",
  "elevator sound",
  "culture",
  "WHISTLEBLOWING",
  "best products showrooms",
  "Shaktigarh",
  "90s jeans",
  "brick pattern",
  "Colorful",
  "Lego brick background",
  "Red fishing rod",
  "Kids fishing rod",
  "Drift wood in greece",
  "Drift wood",
  "Malware",
  "Drawing of cake",
  "Fishing rod",
  "be yourself",
  "celebration",
  "MOUNTAINS",
  "italian salad",
  "family dinner",
  "handwritten letters",
  "paper poetry",
  "italian pizza",
  "Web designer",
  "light playful background music",
  "light atmospheric music",
  "whimsical atmosphere music",
  "windy day music",
  "windy day",
  "whimsical day",
  "tractor tire marks",
  "Little baby sausage dog",
  "Texas football team",
  "the emily morgan hotel san antonio tx",
  "a good day",
  "texas map",
  "Anne Boleyn",
  "angelwof",
  "apec san francisco",
  "Dimitriou's Jazz Alley",
  "gavin newsom",
  "Lionel Messi and the art of living",
  "family photo collection",
  "fortnite",
  "woman performing calf raise",
  "ice cream containers in freezer",
  "ice cream in freezer",
  "crowd booing",
  "sky",
  "BHS STORES",
  "gears",
  "time is money so dont waste.it",
  "Aachen",
  "saints nfl",
  "gen z fashion",
  "hozier",
  "milk powder",
  "white orca",
  "decimated landscape",
  "yankees",
  "scada",
  "public lands extractive industry",
  "vote",
  "Aiblog",
  "cool picture",
  "kittens",
  "paris olympics 2024",
  "colombia environmentalism",
  "DRAWING",
  "divorce",
  'PAPER AND PENCIL"',
  "texturas",
  "wizard of oz",
  "oz",
  "us workers",
  "strawberry",
  "latin america small businesses",
  "Cupcakes",
  "neural network",
  "colorado football",
  "mine lithium",
  "sharks",
  "home depot",
  "baseball",
  "jessica pare",
  "heart",
  "tree hugger",
  "colombia",
  "giant squid",
  "Latin America",
  "mock up",
  "aston villa",
  "Pasir Panjang",
  "thunderstorms at the airport",
  "basketball",
  "puppies",
  "arcade cabinet",
  "community",
  "homes",
  "bird",
  "forest",
  "city skyline",
  "halloween shadows",
  "brain",
  "brows",
  "sketch plan",
  "black and blue butterfly",
  "hotel pools",
  "chevrolet montana",
  "kamala harris",
  "Babies talking",
  "confused woman",
  "infographics",
  "go green",
  "tanzania",
  "Muslim niqabi women",
  "m838te engine",
  "homelessness",
  "music bands",
  "Martin Boyle",
  "tempt",
  "giraffe",
  "lauren elkin",
  "George washington",
  "lifesyle",
  "Peña de Bernal Mexico",
  "autumn",
  "instagram icon",
  "john",
  "naples",
  "iphone 16",
  "riding arena",
  "phlebologist",
  "pangolin",
  "Newton's cradle Clipart",
  "Blood test tubes Clipart",
  "advert",
  "migration camp",
  "migration camp cyprus",
  "migrant camp",
  "ecosystem tasmania",
  "tree",
  "counter strike",
  "robert venturi guild house",
  "sunflowers van gogh",
  "architektur",
  "Akhenaten",
  "eurasian magpie",
  "Affe",
  "La normandie",
  "sim cards",
  "Solar system",
  "Spotted-necked Otter",
  "Brawl stars",
  "How old is Winston Churchill",
  "Haus",
  "Smiley",
  "flowers",
]

export const getRandomQueryTerm = () => randomItem(SAMPLE_QUERY_TERMS)
