FROM python:3.7.4-stretch
RUN mkdir /tmp/output/
RUN mkdir /cccatalog_api_scripts
ENV OUTPUT_DIR=/tmp/output/
ENV FLICKR_API_KEY=notset
RUN apt-get update
RUN apt-get -y install tmux vim
WORKDIR /cccatalog_api_scripts
ADD ./requirements.txt /cccatalog_api_scripts
RUN pip install -r requirements.txt
RUN rm requirements.txt
CMD ["/bin/bash"]