set dotenv-load := false

COLOR := "\\033[0;32m"
NO_COLOR := "\\033[0m"

# Show all available recipes
@_default:
    printf "\n{{ COLOR }}# ES (path: \`docker/es/\`)\n"
    printf "========================={{ NO_COLOR }}\n"
    just --list --unsorted


##########
# Health #
##########

# Check the health of the service
@health host:
    -curl -s -o /dev/null -w '%{http_code}' 'http://{{ host }}/_cluster/health'

# Wait for the service to be healthy
@wait host="localhost:50292":
    # The just command on the second line is executed in the context of the
    # root directory and so must be prefixed with `docker/es/`.
    just ../../_loop \
    '"$(just docker/es/health {{ host }})" != "200"' \
    "Waiting for Elasticsearch to be healthy..."

@check-index index="image" dest="":
    -curl \
      -s \
      -H 'Accept: application/json' \
      'http://localhost:50292/_cat/indices/{{ index }}' \
    | grep -o "{{ (if dest == "" { index } else { dest }) }}" \
    | wc -l \
    | xargs

# Wait for the media to be indexed in Elasticsearch
@wait-for-index index="image" dest="":
    # The just command on the second line is executed in the context of the
    # root directory and so must be prefixed with `docker/es/`.
    just ../../_loop \
    '"$(just docker/es/check-index {{ index }} {{ dest }})" != "1"' \
    "Waiting for index '{{ index }}' to be ready..."
