# Generated by Django 3.2.5 on 2021-08-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_content_provider_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
