export const FETCH_MEDIA_PROVIDERS_END = 'FETCH_MEDIA_PROVIDERS_END'
export const FETCH_MEDIA_PROVIDERS_START = 'FETCH_MEDIA_PROVIDERS_START'
export const SET_PROVIDER_FETCH_ERROR = 'SET_PROVIDER_FETCH_ERROR'
export const SET_MEDIA_PROVIDERS = 'SET_MEDIA_PROVIDERS'
