set dotenv-load := false

COLOR := "\\033[0;35m"
NO_COLOR := "\\033[0m"

# Show all available recipes
@_default:
    printf "\n{{ COLOR }}# NGINX (path: \`docker/nginx/\`)\n"
    printf "==============================={{ NO_COLOR }}\n"
    just --list --unsorted


# Make locally trusted certificates (requires mkcert installed)
cert:
    mkdir -p nginx/certs/
    mkcert \
      -cert-file nginx/certs/openverse.crt \
      -key-file nginx/certs/openverse.key \
      dev.openverse.test localhost 127.0.0.1 ::1
