# Generated by Django 3.2.5 on 2021-07-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_django_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentprovider',
            name='media_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('image', 'Image')], default='image', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentprovider',
            name='provider_name',
            field=models.CharField(max_length=250),
        ),
    ]
