# Generated by Django 3.2.7 on 2021-10-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_filetypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioset',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='The thumbnail for the media.', max_length=1000, null=True),
        ),
    ]
