FROM python:3.9

ENV PYTHONBUFFERED 1

# Install Python dependency management tools
RUN pip install --upgrade pip \
    && pip install --upgrade setuptools \
    && pip install --upgrade pipenv

# Copy all files into the container
COPY . /ingestion_server/
WORKDIR /ingestion_server
ENV PYTHONPATH=$PYTHONPATH:/ingestion_server/

RUN pipenv install --deploy --system --dev
EXPOSE 8002
CMD gunicorn indexer_worker:api -b 0.0.0.0:8002 --reload --access-logfile '-' --error-logfile '-' --chdir ./ingestion_server/
