FROM python:3.9

ENV PYTHONBUFFERED 1

RUN mkdir /worker_state

ENV PYTHONPATH=$PYTHONPATH:/ingestion_server/

WORKDIR /ingestion_server

# Install Python dependency management tools
RUN pip install --upgrade pip \
    && pip install --upgrade setuptools \
    && pip install --upgrade pipenv

# Copy the Pipenv files into the container
COPY Pipfile Pipfile.lock /ingestion_server/

# Install the dependencies system-wide
# TODO: Use build args to avoid installing dev dependencies in production
RUN pipenv install --deploy --system --dev

EXPOSE 8002

CMD ["gunicorn", "-c", "./gunicorn_worker.conf.py"]
