set dotenv-load := false

COLOR := "\\033[0;36m"
NO_COLOR := "\\033[0m"

# Show all available recipes
@_default:
    printf "\n{{ COLOR }}# Ingestion server (path: \`ingestion_server/\`)\n"
    printf "=============================================={{ NO_COLOR }}\n"
    just --list --unsorted


# Install dependencies
install *args="--dev":
    pipenv install {{ args }}

######
# Up #
######

# Bring up services specific to the ingestion server profile
up *flags:
    env COMPOSE_PROFILES="ingestion_server" just ../up {{ flags }}

# Wait for all profile services to be up
wait-up: up
    just wait

##########
# Health #
##########

# Check the health of the service
@health host="ingestion_server:8001":
    just ../curl "-s -o -w %{http_code} {{ host }}"

# Wait for the service to be healthy
@wait host="ingestion_server:8001":
    just ../curl "--retry-connrefused --retry 5 --retry-delay 5 {{ host }}"

#########
# Tests #
#########

# Run ingestion-server tests locally
test-local *args:
    pipenv run ./test/run_test.sh {{ args }}
