"""
# Add Rekognition labels

This DAG inserts labels that were previously generated by Rekognition into the catalog.
For a full description of the DAG, see [this section](https://docs.openverse.org/projects/proposals/rekognition_data/20240530-implementation_plan_augment_catalog_with_rekognition_tags.html#insert-new-rekognition-tags)
of the implementation plan.
"""

import logging


DAG_ID = "add_rekognition_labels"

logger = logging.getLogger(__name__)
