# Generated by Django 2.0.5 on 2018-08-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_image_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('shortened_path', models.CharField(db_index=True, help_text='The path to the shortened URL, e.g. tc3n834. The resulting URL will be shares.cc/tc3n834.', max_length=10, unique=True)),
                ('full_url', models.URLField(max_length=1000, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
