# Generated by Django 2.0.5 on 2018-08-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180803_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelist',
            name='slug',
            field=models.CharField(default=None, help_text='A unique identifier used to make a friendly URL for external downstream API consumers.', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
