# Generated by Django 2.0.8 on 2018-11-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180831_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='perceptual_hash',
        ),
        migrations.AlterField(
            model_name='image',
            name='identifier',
            field=models.UUIDField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='imagelist',
            name='images',
            field=models.ManyToManyField(help_text='A list of identifier keys corresponding to images.', related_name='lists', to='api.Image'),
        ),
    ]
