# Generated by Django 2.0.8 on 2019-01-02 20:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181117_0029'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertags',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='usertags',
            name='image',
        ),
        migrations.RemoveField(
            model_name='usertags',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='usertags',
            name='user',
        ),
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='watermarked',
            field=models.NullBooleanField(),
        ),
        migrations.DeleteModel(
            name='UserTags',
        ),
    ]
