# Generated by Django 2.0.8 on 2019-01-22 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190122_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentprovider',
            name='updated_on',
        ),
    ]
