# Generated by Django 2.2.4 on 2019-09-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190918_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='application',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to='api.ThrottledApplication')
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='application',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to='api.ThrottledApplication')
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='application',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to='api.ThrottledApplication')
        ),
    ]

    def __init__(self, name, app_label):
       super(Migration, self).__init__(name, app_label)
       self.app_label = 'oauth2_provider'
