# Generated by Django 2.2.10 on 2020-05-15 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200429_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagereport',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
