# Generated by Django 2.2.16 on 2021-05-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_sourcelogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentprovider',
            name='filter_content',
            field=models.BooleanField(default=False, verbose_name='Hide content'),
        ),
        migrations.AlterField(
            model_name='contentprovider',
            name='provider_identifier',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='imagereport',
            name='description',
            field=models.TextField(blank=True, help_text='The explanation on why image is being reported.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='imagereport',
            name='identifier',
            field=models.UUIDField(help_text='The ID for image to be reported.'),
        ),
        migrations.AlterField(
            model_name='imagereport',
            name='reason',
            field=models.CharField(choices=[('mature', 'mature'), ('dmca', 'dmca'), ('other', 'other')], help_text='The reason to report image to Creative Commons.', max_length=20),
        ),
    ]
