"""
This file holds string constants for the column names in the image
database, as well as the loading tables in the PostgreSQL DB.
"""
IDENTIFIER = 'identifier'
FOREIGN_ID = 'foreign_identifier'
LANDING_URL = 'foreign_landing_url'
DIRECT_URL = 'url'
THUMBNAIL = 'thumbnail'
WIDTH = 'width'
HEIGHT = 'height'
FILESIZE = 'filesize'
LICENSE = 'license'
LICENSE_VERSION = 'license_version'
CREATOR = 'creator'
CREATOR_URL = 'creator_url'
TITLE = 'title'
META_DATA = 'meta_data'
TAGS = 'tags'
WATERMARKED = 'watermarked'
PROVIDER = 'provider'
SOURCE = 'source'
INGESTION_TYPE = 'ingestion_type'
CREATED_ON = 'created_on'
UPDATED_ON = 'updated_on'
LAST_SYNCED = 'last_synced_with_source'
REMOVED = 'removed_from_source'
