name: openverse/setup-env
description: Setup Openverse CI environment

inputs:
  setup_python:
    default: "true"
    description: Whether to set up Python and install dependencies

  setup_nodejs:
    default: "true"
    description: Whether to set up Node.js and dependencies

  install_recipe:
    default: "install"
    description: The recipe to use to install dependencies

runs:
  using: "composite"
  steps:
    # Just
    - name: Setup just
      uses: taiki-e/install-action@v2
      with:
        tool: just

    # Python
    - name: Setup Python
      if: inputs.setup_python == 'true'
      uses: actions/setup-python@v5
      with:
        # Ensure that it matches `python_version` field in the following files:
        # - `automations/python/Pipfile`
        # - `dead_links/Pipfile`
        python-version: "3.11"

    - name: Setup global Python deps
      if: inputs.setup_python == 'true'
      shell: bash
      # TODO: Try using `pipx` here instead of `pip`.
      run: |
        pip install -U pip
        pip install pipenv pdm

    - name: Setup pnpm
      if: inputs.setup_nodejs == 'true'
      shell: bash
      # Corepack automatically reads `packageManager` field from root `package.json`.
      run: corepack enable pnpm

    - name: Setup Node.js
      if: inputs.setup_nodejs == 'true'
      uses: actions/setup-node@v4
      with:
        node-version-file: "package.json"
        cache: pnpm
        cache-dependency-path: |
          **/pnpm-lock.yaml
          **/.npmrc

    # Install dependencies
    - name: Install dependencies
      if: inputs.install_recipe != ''
      shell: bash
      run: |
        just ${{ inputs.install_recipe }}
