set dotenv-load := false

# Show all available recipes
@_default:
  echo "######################"
  echo "# Python automations #"
  echo "######################"
  just --list --unsorted


# Install dependencies
install:
  pipenv install --dev
