set dotenv-load := false

COLOR := "\\033[0;33m"
NO_COLOR := "\\033[0m"

# Show all available recipes
@_default:
    printf "\n{{ COLOR }}# Python automations (path: \`automations/python/\`)\n"
    printf "=================================================={{ NO_COLOR }}\n"
    just --list --unsorted


# Install dependencies
install *args:
    pdm install {{ args }}

# Run a script
run script *args:
    pdm run {{ script }} {{ args }}
