set dotenv-load := false

COLOR := "\\033[0;33m"
NO_COLOR := "\\033[0m"

# Show all available recipes
@_default:
    printf "{{ COLOR }}######################\n"
    printf "# Python automations #\n"
    printf "######################{{ NO_COLOR }}\n"
    just --list --unsorted


# Install dependencies
install:
    pipenv install --dev
