# Generated by Django 2.0.5 on 2018-08-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_image_watermarked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='foreign_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True, unique=True),
        ),
    ]
