# Generated by Django 2.0.5 on 2018-08-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180831_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelist',
            name='slug',
            field=models.CharField(db_index=True, help_text='A unique identifier used to make a friendly URL for downstream API consumers.', max_length=200, unique=True),
        ),
    ]
