# Generated by Django 3.2.5 on 2021-07-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_audio_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='alt_files',
            field=models.JSONField(blank=True, help_text='JSON describing alternative files for this audio.', null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='watermarked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='watermarked',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
