# Generated by Django 3.2.7 on 2021-10-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_media_thumbnails'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='filetype',
            field=models.CharField(blank=True, help_text='The type of the file, related to the file extension.', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='audioset',
            name='filetype',
            field=models.CharField(blank=True, help_text='The type of the file, related to the file extension.', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='filetype',
            field=models.CharField(blank=True, help_text='The type of the file, related to the file extension.', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='filesize',
            field=models.IntegerField(blank=True, help_text='Number in bytes, e.g. 1024.', null=True),
        ),
        migrations.AlterField(
            model_name='audioset',
            name='filesize',
            field=models.IntegerField(blank=True, help_text='Number in bytes, e.g. 1024.', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='filesize',
            field=models.IntegerField(blank=True, help_text='Number in bytes, e.g. 1024.', null=True),
        ),
    ]
