# Generated by Django 3.2.7 on 2021-10-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_audioset_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='audio_set',
        ),
        migrations.RemoveField(
            model_name='audioset',
            name='identifier',
        ),
        migrations.AddField(
            model_name='audio',
            name='audio_set_foreign_identifier',
            field=models.CharField(blank=True, help_text='Reference to set of which this track is a part.', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='audioset',
            name='provider',
            field=models.CharField(blank=True, db_index=True, help_text='The content provider, e.g. Flickr, Jamendo...', max_length=80, null=True),
        ),
        migrations.AddConstraint(
            model_name='audioset',
            constraint=models.UniqueConstraint(fields=('foreign_identifier', 'provider'), name='unique_foreign_identifier_provider'),
        ),
    ]
