# Generated by Django 3.2.7 on 2021-11-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_audio_audioset_relation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShortenedLink',
        ),
    ]
