# Generated by Django 3.2.12 on 2022-02-16 19:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_singular_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioAddOn',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('audio_identifier', models.UUIDField(help_text='The identifier of the audio object.', primary_key=True, serialize=False)),
                ('waveform_peaks', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='The waveform peaks. A list of floats in the range of 0 -> 1 inclusively.', null=True, size=1500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
