# Generated by Django 4.0.4 on 2022-05-13 09:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_throttledapplication_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='creator',
            field=models.CharField(blank=True, help_text='The name of the media creator.', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='creator_url',
            field=models.URLField(blank=True, help_text='A direct link to the media creator.', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=80), db_index=True, help_text='An array of audio genres such as `rock`, `electronic` for `music` category, or `politics`, `sport`, `education` for `podcast` category', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='audio',
            name='license',
            field=models.CharField(help_text='The name of license for the media.', max_length=50),
        ),
        migrations.AlterField(
            model_name='audio',
            name='license_version',
            field=models.CharField(blank=True, help_text='The version of the media license.', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='tags',
            field=models.JSONField(blank=True, help_text='Tags with detailed metadata, such as accuracy.', null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='tags_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, help_text='List of tags names without detailed metadata.', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='audio',
            name='title',
            field=models.CharField(blank=True, help_text='The name of the media.', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='audioset',
            name='creator',
            field=models.CharField(blank=True, help_text='The name of the media creator.', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='audioset',
            name='creator_url',
            field=models.URLField(blank=True, help_text='A direct link to the media creator.', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='audioset',
            name='title',
            field=models.CharField(blank=True, help_text='The name of the media.', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='creator',
            field=models.CharField(blank=True, help_text='The name of the media creator.', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='creator_url',
            field=models.URLField(blank=True, help_text='A direct link to the media creator.', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.IntegerField(blank=True, help_text='The height of the image in pixels. Not always available.', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='license',
            field=models.CharField(help_text='The name of license for the media.', max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='license_version',
            field=models.CharField(blank=True, help_text='The version of the media license.', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.JSONField(blank=True, help_text='Tags with detailed metadata, such as accuracy.', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='tags_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, help_text='List of tags names without detailed metadata.', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, help_text='The name of the media.', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.IntegerField(blank=True, help_text='The width of the image in pixels. Not always available.', null=True),
        ),
    ]
