# Generated by Django 4.0.4 on 2022-07-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='throttledapplication',
            name='rate_limit_model',
            field=models.CharField(choices=[('standard', 'standard'), ('enhanced', 'enhanced'), ('exempt', 'exempt')], default='standard', max_length=20),
        ),
    ]
