# Generated by Django 4.1 on 2022-10-24 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_audio_model_plural_names'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SourceLogo',
        ),
    ]
