# Generated by Django 4.1.3 on 2022-12-20 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_delete_sourcelogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='audioset',
            field=models.ForeignObject(from_fields=('audio_set_foreign_identifier', 'provider'), null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.audioset', to_fields=('foreign_identifier', 'provider')),
        ),
        migrations.AlterField(
            model_name='audioreport',
            name='identifier',
            field=models.ForeignKey(db_column="identifier", db_constraint=False, help_text='The reference to the audio being reported.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='audio_report', to='api.audio', to_field='identifier'),
        ),
        migrations.AlterField(
            model_name='deletedaudio',
            name='identifier',
            field=models.OneToOneField(db_column="identifier", db_constraint=False, help_text='The reference to the deleted audio.', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='deleted_audio', serialize=False, to='api.audio', to_field='identifier'),
        ),
        migrations.AlterField(
            model_name='deletedimage',
            name='identifier',
            field=models.OneToOneField(db_column="identifier", db_constraint=False, help_text='The reference to the deleted image.', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='deleted_image', serialize=False, to='api.image', to_field='identifier'),
        ),
        migrations.AlterField(
            model_name='imagereport',
            name='identifier',
            field=models.ForeignKey(db_column="identifier", db_constraint=False, help_text='The reference to the image being reported.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='image_report', to='api.image', to_field='identifier'),
        ),
        migrations.AlterField(
            model_name='matureaudio',
            name='identifier',
            field=models.OneToOneField(db_column="identifier", db_constraint=False, help_text='The reference to the sensitive audio.', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='mature_audio', serialize=False, to='api.audio', to_field='identifier'),
        ),
        migrations.AlterField(
            model_name='matureimage',
            name='identifier',
            field=models.OneToOneField(db_column="identifier", db_constraint=False, help_text='The reference to the sensitive image.', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='mature_image', serialize=False, to='api.image', to_field='identifier'),
        ),
        migrations.RenameField(
            model_name="audioreport",
            old_name="identifier",
            new_name="media_obj",
        ),
        migrations.RenameField(
            model_name="deletedaudio",
            old_name="identifier",
            new_name="media_obj",
        ),
        migrations.RenameField(
            model_name="deletedimage",
            old_name="identifier",
            new_name="media_obj",
        ),
        migrations.RenameField(
            model_name="imagereport",
            old_name="identifier",
            new_name="media_obj",
        ),
        migrations.RenameField(
            model_name="matureaudio",
            old_name="identifier",
            new_name="media_obj",
        ),
        migrations.RenameField(
            model_name="matureimage",
            old_name="identifier",
            new_name="media_obj",
        ),
    ]
