# Generated by Django 4.1.7 on 2023-03-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_relational_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='tags_list',
        ),
        migrations.RemoveField(
            model_name='image',
            name='tags_list',
        ),
    ]
