# Generated by Django 4.2.9 on 2024-02-08 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_throttledapplication_post_logout_redirect_uris'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='matureaudio',
            table='api_matureaudio',
        ),
        migrations.AlterModelTable(
            name='matureimage',
            table='api_matureimage',
        ),
    ]
