# Generated by Django 4.2.7 on 2023-12-11 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_throttledapplication_post_logout_redirect_uris"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ImageReport",
            new_name="NsfwReport",
        ),
        migrations.RenameModel(
            old_name="AudioReport",
            new_name="NsfwReportAudio",
        ),
    ]
