# Generated by Django 4.2.7 on 2023-12-11 06:32

import api.models.media
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_rename_imagereport_nsfwreport_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensitiveAudio",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "media_obj",
                    models.OneToOneField(
                        db_column="identifier",
                        db_constraint=False,
                        help_text="The reference to the sensitive audio.",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="sensitive_audio",
                        serialize=False,
                        to="api.audio",
                        to_field="identifier",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sensitive audio",
            },
            bases=(api.models.media.PerformIndexUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SensitiveImage",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "media_obj",
                    models.OneToOneField(
                        db_column="identifier",
                        db_constraint=False,
                        help_text="The reference to the sensitive image.",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="sensitive_image",
                        serialize=False,
                        to="api.image",
                        to_field="identifier",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(api.models.media.PerformIndexUpdateMixin, models.Model),
        ),
        migrations.AlterField(
            model_name="nsfwreport",
            name="media_obj",
            field=models.ForeignKey(
                db_column="identifier",
                db_constraint=False,
                help_text="The reference to the image being reported.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="nsfw_image_report",
                to="api.image",
                to_field="identifier",
            ),
        ),
        migrations.AlterField(
            model_name="nsfwreport",
            name="reason",
            field=models.CharField(
                choices=[
                    ("sensitive", "sensitive"),
                    ("dmca", "dmca"),
                    ("other", "other"),
                ],
                help_text="The reason to report media to Openverse.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="nsfwreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_review", "pending_review"),
                    ("sensitive_filtered", "sensitive_filtered"),
                    ("deindexed", "deindexed"),
                    ("no_action", "no_action"),
                ],
                default="pending_review",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="nsfwreportaudio",
            name="media_obj",
            field=models.ForeignKey(
                db_column="identifier",
                db_constraint=False,
                help_text="The reference to the audio being reported.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="nsfw_audio_report",
                to="api.audio",
                to_field="identifier",
            ),
        ),
        migrations.AlterField(
            model_name="nsfwreportaudio",
            name="reason",
            field=models.CharField(
                choices=[
                    ("sensitive", "sensitive"),
                    ("dmca", "dmca"),
                    ("other", "other"),
                ],
                help_text="The reason to report media to Openverse.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="nsfwreportaudio",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_review", "pending_review"),
                    ("sensitive_filtered", "sensitive_filtered"),
                    ("deindexed", "deindexed"),
                    ("no_action", "no_action"),
                ],
                default="pending_review",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ImageReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("sensitive", "sensitive"),
                            ("dmca", "dmca"),
                            ("other", "other"),
                        ],
                        help_text="The reason to report media to Openverse.",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="The explanation on why media is being reported.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "pending_review"),
                            ("sensitive_filtered", "sensitive_filtered"),
                            ("deindexed", "deindexed"),
                            ("no_action", "no_action"),
                        ],
                        default="pending_review",
                        max_length=20,
                    ),
                ),
                (
                    "media_obj",
                    models.ForeignKey(
                        db_column="identifier",
                        db_constraint=False,
                        help_text="The reference to the image being reported.",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="image_report",
                        to="api.image",
                        to_field="identifier",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AudioReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("sensitive", "sensitive"),
                            ("dmca", "dmca"),
                            ("other", "other"),
                        ],
                        help_text="The reason to report media to Openverse.",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="The explanation on why media is being reported.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "pending_review"),
                            ("sensitive_filtered", "sensitive_filtered"),
                            ("deindexed", "deindexed"),
                            ("no_action", "no_action"),
                        ],
                        default="pending_review",
                        max_length=20,
                    ),
                ),
                (
                    "media_obj",
                    models.ForeignKey(
                        db_column="identifier",
                        db_constraint=False,
                        help_text="The reference to the audio being reported.",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="audio_report",
                        to="api.audio",
                        to_field="identifier",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
