# Generated by Django 4.2.9 on 2024-02-08 18:26

import api.models.media
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_matureaudio_table_alter_matureimage_table'),
    ]

    operations = [
        migrations.RenameModel('MatureImage', 'SensitiveImage'),
        migrations.RenameModel('MatureAudio', 'SensitiveAudio'),
        migrations.AlterField(
            model_name='sensitiveaudio',
            name='media_obj',
            field=models.OneToOneField(db_column='identifier', db_constraint=False, help_text='The reference to the sensitive audio.', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='sensitive_audio', serialize=False, to='api.audio', to_field='identifier'),
        ),
        migrations.AlterField(
            model_name='sensitiveimage',
            name='media_obj',
            field=models.OneToOneField(db_column='identifier', db_constraint=False, help_text='The reference to the sensitive image.', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='sensitive_image', serialize=False, to='api.image', to_field='identifier'),
        ),
    ]
