# Generated by Django 4.2.9 on 2024-02-28 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_rename_mature_to_sensitive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensitiveaudio',
            options={'verbose_name_plural': 'Sensitive audio'},
        ),
    ]
