# Generated by Django 4.2.11 on 2024-04-10 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_user_preferences(apps, schema_editor):
    UserPreferences = apps.get_model("api", "UserPreferences")
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    for user in User.objects.all():
        if not hasattr(user, "userpreferences"):
            UserPreferences.objects.create(user=user)
            user.userpreferences.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0058_moderation_decision'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_user_preferences)
    ]
