# Generated by Django 4.2.11 on 2024-05-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_fill_out_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_set_foreign_identifier',
            field=models.TextField(blank=True, help_text='Reference to set of which this track is a part.', null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='creator',
            field=models.TextField(blank=True, help_text='The name of the media creator.', null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='creator_url',
            field=models.TextField(blank=True, help_text='A direct link to the media creator.', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='foreign_identifier',
            field=models.TextField(blank=True, db_index=True, help_text='The identifier provided by the upstream source.', null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='foreign_landing_url',
            field=models.TextField(blank=True, help_text='The landing page of the work.', null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='thumbnail',
            field=models.TextField(blank=True, help_text='The thumbnail for the media.', null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='title',
            field=models.TextField(blank=True, help_text='The name of the media.', null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='url',
            field=models.TextField(blank=True, help_text='The actual URL to the media file.', max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='audioset',
            name='creator',
            field=models.TextField(blank=True, help_text='The name of the media creator.', null=True),
        ),
        migrations.AlterField(
            model_name='audioset',
            name='creator_url',
            field=models.TextField(blank=True, help_text='A direct link to the media creator.', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='audioset',
            name='foreign_identifier',
            field=models.TextField(blank=True, db_index=True, help_text='The identifier provided by the upstream source.', null=True),
        ),
        migrations.AlterField(
            model_name='audioset',
            name='foreign_landing_url',
            field=models.TextField(blank=True, help_text='The landing page of the work.', null=True),
        ),
        migrations.AlterField(
            model_name='audioset',
            name='thumbnail',
            field=models.TextField(blank=True, help_text='The thumbnail for the media.', null=True),
        ),
        migrations.AlterField(
            model_name='audioset',
            name='title',
            field=models.TextField(blank=True, help_text='The name of the media.', null=True),
        ),
        migrations.AlterField(
            model_name='audioset',
            name='url',
            field=models.TextField(blank=True, help_text='The actual URL to the media file.', max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='creator',
            field=models.TextField(blank=True, help_text='The name of the media creator.', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='creator_url',
            field=models.TextField(blank=True, help_text='A direct link to the media creator.', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='foreign_identifier',
            field=models.TextField(blank=True, db_index=True, help_text='The identifier provided by the upstream source.', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='foreign_landing_url',
            field=models.TextField(blank=True, help_text='The landing page of the work.', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.TextField(blank=True, help_text='The thumbnail for the media.', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.TextField(blank=True, help_text='The name of the media.', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.TextField(blank=True, help_text='The actual URL to the media file.', max_length=1000, null=True, unique=True),
        ),
    ]
