# Generated by Django 4.2.11 on 2024-05-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_convert_varchar_to_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='throttledapplication',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
    ]
