# Generated by Django 4.2.11 on 2024-05-21 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_decision_through_tables'),
        ('api', '0062_throttledapplication_revoked'),
    ]

    operations = [
    ]
