# Generated by Django 4.2.11 on 2024-05-29 01:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_merge_20240521_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='throttledapplication',
            name='privileges',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('max_page_size', 'max_page_size'), ('max_result_count', 'max_result_count')]), default=list, help_text='Restricted features to which this application has been granted privileged access', size=None),
        ),
    ]
