# Generated by Django 4.2.11 on 2024-05-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_merge_20240521_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='creator_url',
            field=models.TextField(blank=True, help_text='A direct link to the media creator.', max_length=2000, null=True, verbose_name='creator URL'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='foreign_landing_url',
            field=models.TextField(blank=True, help_text='The landing page of the work.', null=True, verbose_name='foreign landing URL'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='url',
            field=models.TextField(blank=True, help_text='The actual URL to the media file.', max_length=1000, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='audioset',
            name='creator_url',
            field=models.TextField(blank=True, help_text='A direct link to the media creator.', max_length=2000, null=True, verbose_name='creator URL'),
        ),
        migrations.AlterField(
            model_name='audioset',
            name='foreign_landing_url',
            field=models.TextField(blank=True, help_text='The landing page of the work.', null=True, verbose_name='foreign landing URL'),
        ),
        migrations.AlterField(
            model_name='audioset',
            name='url',
            field=models.TextField(blank=True, help_text='The actual URL to the media file.', max_length=1000, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='image',
            name='creator_url',
            field=models.TextField(blank=True, help_text='A direct link to the media creator.', max_length=2000, null=True, verbose_name='creator URL'),
        ),
        migrations.AlterField(
            model_name='image',
            name='foreign_landing_url',
            field=models.TextField(blank=True, help_text='The landing page of the work.', null=True, verbose_name='foreign landing URL'),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.TextField(blank=True, help_text='The actual URL to the media file.', max_length=1000, null=True, unique=True, verbose_name='URL'),
        ),
    ]
