# Generated by Django 4.2.11 on 2024-05-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0065_throttledapplication_privileges"),
    ]

    operations = [
        migrations.RenameModel(old_name="ContentProvider", new_name="ContentSource"),
        migrations.AlterField(
            model_name="contentsource",
            name="provider_identifier",
            field=models.CharField(
                db_column="provider_identifier", max_length=50, unique=True
            ),
        ),
        migrations.RenameField(
            model_name="contentsource",
            old_name="provider_identifier",
            new_name="source_identifier",
        ),
        migrations.AlterField(
            model_name="contentsource",
            name="provider_name",
            field=models.CharField(db_column="provider_name", max_length=250),
        ),
        migrations.RenameField(
            model_name="contentsource",
            old_name="provider_name",
            new_name="source_name",
        ),
    ]
