# Generated by Django 4.2.11 on 2024-07-04 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0068_remove_audioreport_status_remove_imagereport_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiodecision',
            options={'default_related_name': 'decision'},
        ),
        migrations.AlterModelOptions(
            name='audiodecisionthrough',
            options={'default_related_name': 'decision_through'},
        ),
        migrations.AlterModelOptions(
            name='audioreport',
            options={'default_related_name': 'report'},
        ),
        migrations.AlterModelOptions(
            name='deletedaudio',
            options={'default_related_name': 'deleted_media', 'verbose_name_plural': 'Deleted audio'},
        ),
        migrations.AlterModelOptions(
            name='deletedimage',
            options={'default_related_name': 'deleted_media'},
        ),
        migrations.AlterModelOptions(
            name='imagedecision',
            options={'default_related_name': 'decision'},
        ),
        migrations.AlterModelOptions(
            name='imagedecisionthrough',
            options={'default_related_name': 'decision_through'},
        ),
        migrations.AlterModelOptions(
            name='imagereport',
            options={'default_related_name': 'report'},
        ),
        migrations.AlterModelOptions(
            name='sensitiveaudio',
            options={'default_related_name': 'sensitive_media', 'verbose_name_plural': 'Sensitive audio'},
        ),
        migrations.AlterModelOptions(
            name='sensitiveimage',
            options={'default_related_name': 'sensitive_media'},
        ),
        migrations.AlterField(
            model_name='audiodecision',
            name='media_objs',
            field=models.ManyToManyField(help_text='The audio items being moderated.', related_name='decision', through='api.AudioDecisionThrough', to='api.audio'),
        ),
        migrations.AlterField(
            model_name='audiodecision',
            name='moderator',
            field=models.ForeignKey(help_text='The moderator who undertook this decision.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='audio_decision', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='audiodecisionthrough',
            name='media_obj',
            field=models.ForeignKey(db_column='identifier', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='decision_through', to='api.audio', to_field='identifier'),
        ),
        migrations.AlterField(
            model_name='audioreport',
            name='media_obj',
            field=models.ForeignKey(db_column='identifier', db_constraint=False, help_text='The reference to the audio being reported.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='report', to='api.audio', to_field='identifier'),
        ),
        migrations.AlterField(
            model_name='deletedaudio',
            name='media_obj',
            field=models.OneToOneField(db_column='identifier', db_constraint=False, help_text='The reference to the deleted audio.', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='deleted_media', serialize=False, to='api.audio', to_field='identifier'),
        ),
        migrations.AlterField(
            model_name='deletedimage',
            name='media_obj',
            field=models.OneToOneField(db_column='identifier', db_constraint=False, help_text='The reference to the deleted image.', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='deleted_media', serialize=False, to='api.image', to_field='identifier'),
        ),
        migrations.AlterField(
            model_name='imagedecision',
            name='media_objs',
            field=models.ManyToManyField(help_text='The image items being moderated.', related_name='decision', through='api.ImageDecisionThrough', to='api.image'),
        ),
        migrations.AlterField(
            model_name='imagedecision',
            name='moderator',
            field=models.ForeignKey(help_text='The moderator who undertook this decision.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='image_decision', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imagedecisionthrough',
            name='media_obj',
            field=models.ForeignKey(db_column='identifier', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='decision_through', to='api.image', to_field='identifier'),
        ),
        migrations.AlterField(
            model_name='imagereport',
            name='media_obj',
            field=models.ForeignKey(db_column='identifier', db_constraint=False, help_text='The reference to the image being reported.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='report', to='api.image', to_field='identifier'),
        ),
        migrations.AlterField(
            model_name='sensitiveaudio',
            name='media_obj',
            field=models.OneToOneField(db_column='identifier', db_constraint=False, help_text='The reference to the sensitive audio.', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='sensitive_media', serialize=False, to='api.audio', to_field='identifier'),
        ),
        migrations.AlterField(
            model_name='sensitiveimage',
            name='media_obj',
            field=models.OneToOneField(db_column='identifier', db_constraint=False, help_text='The reference to the sensitive image.', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='sensitive_media', serialize=False, to='api.image', to_field='identifier'),
        ),
    ]
