# Generated by Django 4.2.11 on 2024-09-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_remove_audioreport_status_remove_imagereport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsource',
            name='source_identifier',
            field=models.CharField(db_column='provider_identifier', max_length=80, unique=True),
        ),
    ]
