# Generated by Django 4.2.11 on 2024-09-25 16:38

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_throttledapplication_allowed_origins_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'ordering': ['-created_on'], 'verbose_name': 'audio track', 'verbose_name_plural': 'audio tracks'},
        ),
        migrations.AlterModelOptions(
            name='deletedaudio',
            options={'verbose_name': 'deleted audio track', 'verbose_name_plural': 'deleted audio tracks'},
        ),
        migrations.AlterModelOptions(
            name='sensitiveaudio',
            options={'verbose_name': 'sensitive audio track', 'verbose_name_plural': 'sensitive audio tracks'},
        ),
    ]
