#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Generate a new openverse.pot file if en.json has changes
TRANSFILE=src/locales/en.json
POTFILE=src/locales/po-files/openverse.pot
CHANGED=$(git diff --staged --name-only HEAD)

if [[ "$CHANGED" == *"$TRANSFILE"* ]] && [[ "$CHANGED" != *"$POTFILE"* ]]; then
  npm run i18n:generate-pot
  git add $POTFILE
fi

# Lint staged files
npx lint-staged
