"""Switch to boolean search rating instead of 1-5 star rating

Revision ID: 7695412f8a64
Revises: 54e56668b66a
Create Date: 2019-11-07 14:13:50.764789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7695412f8a64'
down_revision = '54e56668b66a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_rating_event', sa.Column('relevant', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_search_rating_event_relevant'), 'search_rating_event', ['relevant'], unique=False)
    op.drop_column('search_rating_event', 'rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_rating_event', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_search_rating_event_relevant'), table_name='search_rating_event')
    op.drop_column('search_rating_event', 'relevant')
    # ### end Alembic commands ###
